### ISSUE TITLE
how can i set play_video‘s width and height?

### ISSUE THREAD

**Issue by 329521** [JesbinJose/100days-of-learning-python#1]
# run on win11
The error message is：
···
NVIDIA GeForce GTX 1070 Ti
media_kit: ANGLESurfaceManager: Direct3D Feature Level: 11_0
1 1
media_kit: VideoOutput: Create Texture: 1624346223008
Another exception was thrown: A RenderFlex overflowed by 99780 pixels on the bottom.
media_kit: VideoOutput: Using H/W rendering.
flutter: VideoOutput.Resize
flutter: {handle: 1623948669968, id: 1624346223008, rect: {height: 0, left: 0, top: 0, width: 0}}
flutter: NativeVideoController: Texture ID: 1624346223008
flutter: media_kit: wakelock: _count = 1
flutter: media_kit: wakelock: _count = 0
flutter: media_kit: wakelock: _count = 1
flutter: media_kit: wakelock: _count = 0
960 400
media_kit: VideoOutput: Free Texture: 1624346223008
media_kit: ANGLESurfaceManager: Direct3D Feature Level: 11_0
media_kit: VideoOutput: Create Texture: 1623987633952
flutter: VideoOutput.Resize
flutter: {handle: 1623948669968, id: 1623987633952, rect: {height: 400, left: 0, top: 0, width: 960}}
Another exception was thrown: You need to initlize it before using
Another exception was thrown: You need to initlize it before using
Another exception was thrown: A RenderFlex overflowed by 99780 pixels on the bottom.···
the video can play，But the set width and height do not take effect and the error message.

**Comment by JesbinJose** [comment]
bro actually i think you have to post it in the play_video package repo this is not the repo that you are looking for also i will try to fix it as soon as possible

**Comment by 329521** [comment]
sorry,have a mistake
